### ISSUE TITLE
MP4 over Thin fails on iPad

### ISSUE THREAD

**Issue by ain** [macournoyer/thin#250]
I'm trying to access MP4 directly with iPad on the Thin server. The response seems to be alright:

```
Started GET "/assets/xmas2014_de.mp4" for 192.168.1.201 at 2014-12-03 13:36:37 +0100
Served asset /xmas2014_de.mp4 - 200 OK (0ms)
```

but the playback fails.

Checking the file with curl gives:

```
$ curl -I http://192.168.1.160:3000/assets/xmas2014_de.mp4
HTTP/1.1 200 OK
Content-Type: video/mp4
Content-Length: 7439974
Cache-Control: public, must-revalidate
Last-Modified: Wed, 03 Dec 2014 09:33:36 GMT
ETag: "6be0b0ce0e7caeefcd51a9a7beeb01eb"
X-UA-Compatible: IE=Edge
X-Request-Id: c7abce900c589919fd7056168df47d90
X-Runtime: 0.001271
Connection: keep-alive
Server: thin
```

`config/initializers/mime_types.rb` stands:

``` ruby
Rack::Mime::MIME_TYPES.merge!({
  ".ogg"     => "application/ogg",
  ".ogx"     => "application/ogg",
  ".ogv"     => "video/ogg",
  ".oga"     => "audio/ogg",
  ".mp4"     => "video/mp4",
  ".m4v"     => "video/mp4",
  ".mp3"     => "audio/mpeg",
  ".m4a"     => "audio/mpeg"
})
```

Although I experienced the same on WEBrick, **on Apache the MP4 works**.

**Comment by yongcomeon** [comment]
iPad only support MP4 encoded with MPEG-4 or H.264. If your MP4 is encoded with other codec, it will not supported by iPad.

In order to play all MP4s on iPad, iPad2, iPad 3, iPad 4, iPad mini, iPad Air, we need to convert MP4 to iPad default codecs. iDealshare VideoGo is just the right software to convert MP4 to iPad default codecs. Besides iDealshare VideoGo can also convert other formats, like WMV, AVI, MOV, VOB, MKV, MTS, MPEG, 3GP,etc. to iPad supported MP4.

**Comment by gretel** [comment]
@yongcomeon, ffmpeg and various other tools are freely available (no trialware).

**Comment by ain** [comment]
@yongcomeon @gretel of course I'm aware how to work with MP4 on iOS, this is not the question. If you read the report in detail, you'll also notice, the same request succeeds on Apache. The problem is server-specific, not about format.
