### ISSUE TITLE
Rails Server Exiting `close': Bad file descriptor (Errno::EBADF)

### ISSUE THREAD

**Issue by amitkushwahanavyug** [macournoyer/thin#287]
I am getting this issue on any thin version like 1.6.1 and also on latest version 1.6.4 on windows  7 machine. 

C:/RAILSINSTALLER/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.3-x86-ming
w32/lib/em/pure_ruby.rb:330:in `close': Bad file descriptor (Errno::EBADF)
        from C:/RAILSINSTALLER/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/eventmachine-1
.0.3-x86-mingw32/lib/em/pure_ruby.rb:330:in`block in run'
        from C:/RAILSINSTALLER/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/eventmachine-1
.0.3-x86-mingw32/lib/em/pure_ruby.rb:330:in `each'
        from C:/RAILSINSTALLER/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/eventmachine-1
.0.3-x86-mingw32/lib/em/pure_ruby.rb:330:in`ensure in run'
        from C:/RAILSINSTALLER/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/eventmachine-1
.0.3-x86-mingw32/lib/em/pure_ruby.rb:333:in `run'
        from C:/RAILSINSTALLER/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/eventmachine-1

**Comment by macournoyer** [comment]
Perhaps port was already in use?

**Comment by GREPY** [comment]
Which port do you mean? I seem to have the same issue...

**Comment by awdrake** [comment]
I just ran across this issue myself -
the problem is that thin > 1.6.3 is requiring eventmachine > 1.0.3 the newer versions don't reconize one of the file extensions when running in x86-mingw environment so in your gemfile:
Set thin <= 1.6.3
at command line - gem uninstall eventmachine (all versions) > 1.0.3
(the problem is related to eventmachine versions > 1.0.3)
gem install eventmachine 1.0.3
replace eventmachine /em/pure_ruby with gem 'eventmachine', '1.0.3' in your gemfile
to prevent lockout you may need to remove the eventmachine line from your gemfile.lock before a bundle install is attempted
