### ISSUE TITLE
configuration option to allow web app exceptions to propagate

### ISSUE THREAD

**Issue by agibralter** [macournoyer/thin#50]
It would be useful if Thin had a configuration option that allowed for Exceptions raised in a web app to propage beyond Thin. In particular, in testing frameworks such as Cucumber(+Capybara), Exceptions raised in web apps are silently logged and ignored; the request loads as blank page, and it makes it difficult to figure out the source of the error.

I opened an issue for Capybara: https://github.com/jnicklas/capybara/issues/329 but decided it would make more sense if we didn't have to monkey patch Thin to achieve this.

What I'm suggesting is that https://github.com/macournoyer/thin/blob/master/lib/thin/connection.rb#L130 could have something like this:

```
raise $! if raise_errors?
```

Any thoughts?

**Comment by janko-m** [comment]
I would also like the same feature. I'm writing integration tests for my Grape application, and unfortunately rack-test is just too "fake" for me (I haven't managed to send JSON request bodies), and isn't maintained for over a year now. So in tests I decided to start up the server in a separate thread, and use Faraday to send requests to it.

```rb
server = Thin::Server.new(MyApp, "localhost", 8080)
Thread.new { server.start } and (:wait until server.running?)
```

You're right, none of the web servers implement an opt-in way of not rescuing every exception. I just don't know how to solve my problem then. I do get an error in my tests that something is wrong when Faraday attempts to parse response body as JSON:

```
757: unexpected token at 'Internal server error'
```

But it's obviously not enough information. I could theoretically make some kind of `rescue_from` and dump the message and backtrace into the body, but it would be great if the error could just propagate, since my test is already running in the same process as the server.

**Comment by janko-m** [comment]
Nevermind, managed to find a blog post for sending request bodies as JSON, now I can go back to rack-test.

http://jasonincode.com/rack_test_and_json/
